### ISSUE TITLE
Downsampling or Striding Data

### ISSUE THREAD

**Issue by lukecampbell** [ooici/coverage-model#163]
Is there an interface for downsampling or striding data? I'm concerned that if I put the stride logic in the application layer that we'll run hit major performance issues. It's very possible that it exists and I just missed it.

**Comment by caseybryant** [comment]
Needs to be added.  It is pretty straight-forward.  I'll add it.

**Comment by lukecampbell** [comment]
I was going to try to do a mini version in the application just to get erddap to work with striding but I'll wait.

**Comment by caseybryant** [comment]
Are your needs as simple as 'every Xth element'?

**Comment by lukecampbell** [comment]
Yeah that works, from that I can get everything else I would need. To the best of my knowledge, only visualization uses striding.

**Comment by caseybryant** [comment]
Resolved with coverage_model commit fc6910bbef77b21d6177d085dbfe9d5008440ec0

**Comment by lukecampbell** [comment]
Perfect, thanks.
