### ISSUE TITLE
is_empty

### ISSUE THREAD

**Issue by lukecampbell** [ooici/coverage-model#172]
Add an is_empty() method to the Coverage interface and remove insert_timesteps and num_timesteps.

We came to the same conclusion, that the number of timesteps for a coverage is irrelevant and misleading.

**Comment by caseybryant** [comment]
I implemented the is_empty method in commit .  Your note indicates that you want the insert_timesteps and num_timesteps methods removed as well, but we didn't talk about this.  I'm okay with removing them.  Is that what you want?

**Comment by lukecampbell** [comment]
Yeah can we get rid of them?

It'll cause a few test hiccups but they're misleading now, I think.

**Comment by caseybryant** [comment]
Insert time steps has been removed.  I retooled num_timesteps.  Spins through all the data and calculates the number of time steps.  It's accurate, but I can remove it if you thin it is still misleading.
