### ISSUE TITLE
Array types return object arrays

### ISSUE THREAD

**Issue by lukecampbell** [ooici/coverage-model#174]
For now it's ok but in the future, I think it would make the interface better if it returned a proper numpy array with a definite shape. Mostly this is to assist the pydap handler in properly formatting the array for ERDDAP.

**Comment by lukecampbell** [comment]
If the issue is marked as wontfix, I'll update the application code to translate it into a numpy array, but I just need a consensus.

**Comment by caseybryant** [comment]
This will be fixed as part of the parameter type compression changes.

**Comment by lukecampbell** [comment]
https://github.com/caseybryant/coverage-model/pull/12

**Comment by caseybryant** [comment]
This is now corrected.  Be aware that I do type checking on insert for ArrayType.  You can only insert an ndarray with 2D shape.  The second dimension must be equal to the inner_length defined in the parameter type, and the dtype must match the dtype of the parameter type.

Look at test_postgres_storage:TestPostgresStorageInt.test_array_types and test_sparse_arrays for examples.
