### ISSUE TITLE
Complex Coverage

### ISSUE THREAD

**Issue by lukecampbell** [ooici/coverage-model#181]
An interface (which we've typically referred to as the complex coverage) that can aggregate one or more coverages.
- Complex Coverages are read only
- Complex Coverages have their own parameter dictionaries
- Queries return fill values for missing parameters
- A first pass solution would be array concatenation
- (second pass) ERDDAP will need proper slicing support, i.e. if all the coverage's parameter values were treated as a single array and sliced, that is the same value that is returned from the complex coverage.

**Comment by caseybryant** [comment]
Reference coverage temporal windows are now supported.

One caveat - it is up to the user to ensure that windows don't overlap.  Currently, if the windows overlap, the overlapping data will be reported twice.

For examples, look at test:
coverage_model.test.test_complex_coverage:TestNewComplexCoverageInt.test_get_parameters_with limiting_extents

**Comment by caseybryant** [comment]
Luke, can you elaborate on ERDDAP proper slicing support.  I'm not sure what you're looking for.

**Comment by lukecampbell** [comment]
So, in summary, ERDDAP expects an exact number of values to be returned and if that number doesn't match it's expected number it throws an error.

If our dataset has 1024 values, and we stride it by 3 it will expect exactly 341 values. The reason I bring this up is because when I hacked together an aggregator for R2 before the complex coverage was ready then, I ran into this problem because simply concatenating the arrays together generally caused strided queries to fail without some smarter logic.

**Comment by lukecampbell** [comment]
Casey, that's absolutely fine behavior, the client shouldn't be defining overlapping windows. I'll add some logic into the API service method for this as a brief check but if deployments overlap for a site, we have big issues. The implication is that two devices were deployed to the exact same location at the same time, and to the best of my knowledge that doesn't happen and we don't need to deal with it. But, with that said, I've been wrong before.

**Comment by lukecampbell** [comment]
I made a guess and added "rcov_extents" to the Coverage schema, can you check it and make sure it's right?
https://github.com/caseybryant/ion-definitions/pull/1

**Comment by lukecampbell** [comment]
also, so far so good, looks promising!

**Comment by lukecampbell** [comment]
https://github.com/caseybryant/coverage-model/pull/13

This was mostly for familiarization purposes, but might as well include the test if it doesn't break anything.

**Comment by caseybryant** [comment]
I uncommented the 'stretch case' you identified in test_attributes.  I fixed data striding in complex coverage to make the test complete successfully.  Can you verify the resolution degradation/striding solution is what you're looking for? 

If it is, does this meet the stated ERDAP requirement?

**Comment by lukecampbell** [comment]
Yes, that's what ERDDAP is looking for.

**Comment by caseybryant** [comment]
Excellent.  At this point, I think I hit all the points for complex coverage.

Unless you come back with something I missed, testing issues, or improvement requests, I will consider complex coverage complete.

**Comment by lukecampbell** [comment]
I'm pretty sure it's complete. I'm in the process of replacing the stubs with the Complex Coverage stuff. Everything's working well.
