### ISSUE TITLE
Ragged Array Support

### ISSUE THREAD

**Issue by lukecampbell** [ooici/coverage-model#182]
- Parameter Type for Ragged Arrays
- list of lists for return type (I'm open to suggestions too)

**Comment by caseybryant** [comment]
By list of lists do you mean a numpy ndarray of lists?

**Comment by lukecampbell** [comment]
``` python
a = [[1,2,3],
       [3,2],
       [0,9,10]]
```

Something like this maybe, again, I'm open to suggestions. I think that cramming objects inside numpy arrays is clunky and extremely prone to errors, based on my experience with ragged arrays in the R2 Coverage Model. It's generally difficult and annoying to work with numpy arrays that have an inner type of numpy object and are ragged in nature. 

I'm actually almost of the mindset of making a new python class just for this end

something like

``` python
class RaggedArray(object):
    inner_shapes = []
    outer_length = 0
    array = []

    def __init__(self, initializer):
        for iterable in initializer:
            inner_shapes.append(len(iterable))
            array.append(iterable)
            outer_length += 1

    def __len__(self):
        return outer_length
```

**Comment by caseybryant** [comment]
I agree that numpy arrays don't handle ragged arrays well. It's going to be messy no matter what we do, though.  If we don't use numpy for ragged arrays, then there is a special interface for on parameter type. If we use numpy arrays, data is stored as objects. 
What if I implement a converter for ragged array types (or any type for that matter) that converts the numpy array to a list of objects with appropriate typing.
This way, we can maintain the interface, but you can also get what you're looking for by running data through the converter.

**Comment by caseybryant** [comment]
Also, putting the data into numpy arrays is going to be more performant inside coverage model. We do lots of manipulations, and numpy gives us C like speed and minimizes copies.

**Comment by lukecampbell** [comment]
Please be careful, I know very well and clearly that numpy's C-API doesn't handle ragged arrays very well, it treats it as one contiguous array of Py_Objects... and what appears to be intuitive approaches to problem solving can be very problematic.

**Comment by lukecampbell** [comment]
http://numpy-discussion.10968.n7.nabble.com/ragged-array-implimentation-td12382.html

**Comment by lukecampbell** [comment]
We don't need to get carried away on ragged arrays right now, I think.

**Comment by caseybryant** [comment]
Implemented RaggedArrayType as a 1D array of objects.  Implementing more advanced array types is not trivial.  There may be performance issues with 1D array of objects, but it works, and gets us moving forward.

Type checking on insertion forces the inserted array to be a 1D array of objects.  Use RaggedArrayType.create_ragged_array to ensure the array is constructed properly (i.e. np.array([ (1,2), (3,4) ], dtype=object) creates a (2,2) array of objects.  create_ragged_array converts the 2D array to a 1D array of objects.

**Comment by lukecampbell** [comment]
looks good
