### ISSUE TITLE
Sparse Arrays are represented as record arrays instead of ndarrays

### ISSUE THREAD

**Issue by lukecampbell** [ooici/coverage-model#183]
Here's a pull request showing the test.
https://github.com/caseybryant/coverage-model/pull/11

Parameter functions, data retriever and pydap don't deal with record arrays. Now, I can update all of these places to deal with record arrays but it would be better, I think, if the types are consistently represented as numpy arrays where feasible.

**Comment by caseybryant** [comment]
This may be fixed.  Look at test_postgres_storage:TestPostgresStorageInt.test_sparse_arrays to see if it is now the way you expect.
