### ISSUE TITLE
Complex Coverage referencing empty coverages

### ISSUE THREAD

**Issue by lukecampbell** [ooici/coverage-model#186]
Could we add support so that the referenced coverages can be empty and later be filled in?

I think, when the planning preload is done we'll have complex coverages created that reference empty simplex coverages. The extents will be defined from like March 2014 to November 2014 or something but the simplexes will be empty until we start streaming data.

**Comment by lukecampbell** [comment]
Verified with the test, I added one more piece to it:
https://github.com/caseybryant/coverage-model/pull/15

**Comment by caseybryant** [comment]
Test is merged. I believe this issue is resolved.
